services:
    mosquitto:
        image: eclipse-mosquitto
        ports:
            - 1883:1883
            - 8883:8883
            - 9001:9001
        volumes:
            - ./passwd_file:/mosquitto/passwd_file
            - ./config/mosquitto.conf:/mosquitto/config/mosquitto.conf
            - ./data:/mosquitto/data
            - ./log:/mosquitto/log
        networks:
            - mosquitto
networks:
    mosquitto:
        name: mosquitto
        driver: bridge